### ISSUE TITLE
[IMPROVING] Next Update for v0.3.x

### ISSUE THREAD

**Issue by ikr4-m** [mplus-oss/mdrop#6]
*Reserved for next update*

## To-do
- [x] [HOTFIX] Add check auth parse if there's no authentication file.
- [x] [HOTFIX] Change output flag behavior for multiple file and single file.
- [x] Add debug environment for print parseError on ID.
- [x] Hardening authentication on tunnel (if private mode is on).
- [ ] MacOS runner & deploy (without reusable workflow)
- [ ] Windows runner & deploy (without reusable workflow)

**Comment by ikr4-m** [comment]
*We still thinking about next patch name or extending "Nokotan" version name.*

## To-do (Past v0.2)
- [x] Improving approval system before receiving the file.
- [x] Multi authentication provider.
- [x] Changing all flags from camelCase to kebab-case ~~because our developer feel threatened and disgusted at the same time.~~
- [x] Change tunnel image build workflow using golang-alpine container.
- [x] Add Github Action to release app on new mirror internal S3 Bucket. (it's public, don't worry)
- [x] Add unit testing to check build is successful or not.
- [x] Create version checking.
- [ ] ~~Linux (ARM) support.~~
- [ ] ~~Windows (AMD64) support.~~
